config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :profiles do
    member do
      get 'target'
    end
  end

  resources :campaigns do
    resources :votes
  end

  resources :votes, only: [] do
    collection do
      get :next
    end
  end

  get 'results' => 'campaigns#results'
  get 'come_back_later' => 'campaigns#come_back_later'
  get 'finish_voting' => 'campaigns#finish_voting'
  get 'users/sign_in' =>  "home#index"
  get 'users/sign_up' =>  "home#index"

  resources :pictures

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: "home#index"
  get 'policy' => 'home#policy'
  get 'beer' => 'home#beer'

  post 'subscribe', to: 'home#subscribe', as: :subscribe
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :user
  belongs_to :picture
  has_many :votes
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
 before_action :authenticate_user!

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = current_user.campaigns.new(campaign_params)
    @campaign.save
    redirect_to next_votes_path
  end

  def show
    @user = current_user
    @campaign = Campaign.find(params[:id])
    if @campaign.votes.where(user: current_user).any? || !current_user.targets.include?(@campaign.user)
      redirect_to next_votes_path
    else
      @votes = @campaign.votes.new
    end
  end

  def finish
    @campaign.status = false
  end

  def results
    @campaign = current_user.campaigns.first
    if current_user.target_gender && current_user.target_min_age && current_user.target_max_age && current_user.city
      redirect_to profile_path(current_user.id) unless current_user.campaigns.first
    else
      redirect_to target_profile_path(current_user.id)
    end
  end

  def come_back_later
    if current_user.target_gender && current_user.target_min_age && current_user.target_max_age && current_user.city
      redirect_to profile_path(current_user.id) unless current_user.campaigns.first
    else
      redirect_to target_profile_path(current_user.id)
    end
  end

  def finish_voting
  end

  private

  def campaign_params
    params.require(:campaign).permit(:picture_a_id, :picture_b_id, :user_id)
  end

end

app/views/campaigns/_campaign_results.html.erb
<% content_for(:title) do %>
   Results
<% end %>

<h1> <strong>Your results</strong> </h1>


<div class="container">

  <div class="row">

    <div class="col-xs-10 col-xs-offset-1 col-md-offset-1 col-md-5">
      <div class="text-center">
        <div class="text-block" style="padding-bottom:0px;">
          <%= image_tag Picture.find(@campaign.picture_a_id).file,  :class => "picture-results" %><br/>
          <h1 style="padding-bottom:0px;"><%= 100*(@campaign.votes.where(voted_picture_id: @campaign.picture_a_id).length)/@campaign.votes.length %>%<h1>
        </div>
      </div>
    </div>
    <div class="col-xs-10 col-md-5">
      <div class="text-center">
        <div class="text-block"  style="padding-bottom:0px;">
          <%= image_tag Picture.find(@campaign.picture_b_id).file, :class => "picture-results" %><br/>
          <h1 style="padding-bottom:0px;"><%= 100*(@campaign.votes.where(voted_picture_id: @campaign.picture_b_id).length)/@campaign.votes.length %>%</h1>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="text-center">

  <a href="#" onclick="window.open('http://www.facebook.com/sharer/sharer.php?u=http://tindergenius.com','test','toolbar=0, status=0, top=300, left=500, width=500, height=400');return false" class="btn btn-warning btn-lg button-text">
    <i class="fa fa-facebook-square" style="color: white"></i><strong> Share</strong>
  </a>

  <a href="https://twitter.com/intent/tweet?original_referer=http%3A%2F%2Flocalhost%3A3000%2Fcome_back_later&amp;text=What%20picture%20should%20you%20use%20on%20Tinder%3F%20%40Tinder_Genius%20gives%20you%20the%20answer%3A&amp;tw_p=tweetbutton&amp;url=http%3A%2F%2Fwww.tindergenius.com" class="btn btn-success btn-lg button-text">
    <i class="fa fa-twitter" style="color: #139ae9"></i><strong style="color: #333333"> Tweet</strong>
  </a>

  <%= link_to beer_path, class: "btn btn-info btn-lg" do %>
      <i class="fa fa-beer"></i><strong> Thank us with a beer!</strong>
  <% end %>

</div>


<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/campaigns/_no_results_yet.html.erb
<% content_for(:title) do %>
   Wait for your results
<% end %>

<h1>Your results are not ready yet!</h1>

<div class="progress-pie-chart" data-percent="<%= (((@campaign.votes.length + 1) / 6.0) * 100) %>">
  <div class="ppc-progress">
    <div class="ppc-progress-fill"></div>
  </div>
  <div class="ppc-percents">
    <div class="pcc-percents-wrapper">
      <span>%</span>
    </div>
  </div>
</div>

<br/>
<div class="text-under-title text-center" style="font-family: Source Sans Pro">
  <%= 5 - @campaign.votes.length %>
  <% if current_user.target_gender == "male" %>
    men
  <% else %>
    women
  <% end %>
  still need to vote on your pictures to ensure the reliability of the test! :)
</div>
<br/>

<div class="text-under-title text-center" style="font-family: Source Sans Pro">
  To get your results faster:
</div>
<br/>

<div class="text-center">

  <%= link_to next_votes_path, class: "btn btn-info btn-lg" do %>
      <i class="fa fa-bolt"></i><strong> Vote more!</strong>
  <% end %>

  <a href="#" onclick="window.open('http://www.facebook.com/sharer/sharer.php?u=http://tindergenius.com','test','toolbar=0, status=0, top=300, left=500, width=500, height=400');return false" class="btn btn-warning btn-lg button-text">
    <i class="fa fa-facebook-square" style="color: white"></i><strong> Share</strong>
  </a>

  <a href="https://twitter.com/intent/tweet?original_referer=http%3A%2F%2Flocalhost%3A3000%2Fcome_back_later&amp;text=What%20picture%20should%20you%20use%20on%20Tinder%3F%20%40Tinder_Genius%20gives%20you%20the%20answer%3A&amp;tw_p=tweetbutton&amp;url=http%3A%2F%2Fwww.tindergenius.com" class="btn btn-success btn-lg button-text">
    <i class="fa fa-twitter" style="color: #139ae9"></i><strong style="color: #333333"> Tweet</strong>
  </a>

</div>


<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>


<!--
<i class="fa fa-bolt"></i><%= link_to "Vote more", next_votes_path %>


<a target="blank" href="https://www.google.com/maps?q=mojitos+near+<%= current_user.city.gsub(/\s/,'+').gsub(/\,/,'+') %>" class="btn btn-info btn-lg">
          <i style="color: white" class="button-text"></i><i class="fa fa-thumbs-up"></i><strong> Oh yeah!</strong>
        </a> -->

app/views/campaigns/come_back_later.html.erb
<% content_for(:title) do %>
   Come Back
<% end %>

<h1 id="title-no-pic-to-vote-on"> <strong>Sorry - there's no more pictures to vote on, <%= current_user.first_name %>.</strong> </h1>

<div class="text-center">
  <img src="http://s29.postimg.org/ua2zj5ejb/empty_picture_tg.png" height="152" width="180"><br/><br/>
</div>

<div class="text-under-title text-center" style="font-family: Source Sans Pro">
  <p>Come back later! In the meantime, you can:</p>
</div>

<div class="container">

  <div class="row">

    <div class="col-xs-10 col-xs-offset-1 col-md-offset-1 col-md-5">
      <div class="text-center">
        <div class="text-block">
          <img src="http://s24.postimg.org/blnz0scb9/present.png" height="200" width="200"><br/>
            <p class="text-center">1. Help your friends get more matches on Tinder<br/>(they'll love you for life)</p>
        </div>
        <a href="#" onclick="window.open('http://www.facebook.com/sharer/sharer.php?u=http://tindergenius.com','test','toolbar=0, status=0, top=300, left=500, width=500, height=400');return false" class="btn btn-warning btn-lg button-text">
          <i class="fa fa-facebook-square" style="color: white"></i><strong> Share</strong>
        </a>
        <a href="https://twitter.com/intent/tweet?original_referer=http%3A%2F%2Flocalhost%3A3000%2Fcome_back_later&amp;text=What%20picture%20should%20you%20use%20on%20Tinder%3F%20%40Tinder_Genius%20gives%20you%20the%20answer%3A&amp;tw_p=tweetbutton&amp;url=http%3A%2F%2Fwww.tindergenius.com" class="btn btn-success btn-lg button-text">
          <i class="fa fa-twitter" style="color: #139ae9"></i><strong style="color: #333333"> Tweet</strong>
        </a>
      </div>
    </div>
    <div class="col-xs-10 col-md-5">
      <div class="text-center">
        <div class="text-block">
          <img src="http://s30.postimg.org/jzfhlp5c1/mojito.png" height="200" width="200"><br/>
          <p class="text-center">2. Go drink a Mojito<br/>(with your Tinder match?)</p>
        </div>
        <a target="blank" href="https://www.google.com/maps?q=mojitos+near+<%= current_user.city.gsub(/\s/,'+').gsub(/\,/,'+') %>" class="btn btn-default btn-lg">
          <i style="color: white" class="button-text"></i><i class="fa fa-thumbs-up"></i><strong> Oh yeah!</strong>
        </a>
      </div>
    </div>

  </div>
</div>

<div class="text-center" style="font-family: Source Sans Pro; padding-top:40px;padding-bottom:20px;">
  <% if user_signed_in? %>
    <%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %>
  <% end %>
</div>


<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/campaigns/finish_voting.html.erb
<% content_for(:title) do %>
   Results
<% end %>

<h1 id="title-no-pic-to-vote-on"> <strong>We'll email you the results soon, <%= current_user.first_name %>.</strong> </h1>

<div class="text-center">
  <img src="http://s27.postimg.org/s9a0alr9v/Screen_Shot_2014_12_04_at_10_25_25.png" height="137" width="120"><br/><br/>
</div>

<div class="text-under-title text-center" style="font-family: Source Sans Pro">
  <p><strong style="color: white;">To accelerate the process, you can:</strong></p><br/>
</div>

<div class="container">

  <div class="row">

    <div class="col-md-4 col-xl-3">
      <div class="text-center">
        <div class="text-block">
          <img src="http://s14.postimg.org/acfu38atd/Screen_Shot_2014_12_04_at_11_07_23.png" height="200" width="200"><br/>
          <p class="text-center">1. Continue voting<br/><span style="font-size: 16px;">(the more you vote the faster you'll know)</span></p>
        </div>
        <div>
          <%= link_to next_votes_path, class: "btn btn-info btn-lg" do %>
            <i class="fa fa-bolt"></i><strong> Vote more!</strong>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-4 col-xl-3">
      <div class="text-center">
        <div class="text-block">
          <img src="http://s24.postimg.org/blnz0scb9/present.png" height="200" width="200"><br/>
            <p class="text-center">2. Bring your friends on Tinder Genius<br/><span style="font-size: 16px;">(they'll love you for life)</span></p>
        </div>
        <a href="#" onclick="window.open('http://www.facebook.com/sharer/sharer.php?u=http://tindergenius.com','test','toolbar=0, status=0, top=300, left=500, width=500, height=400');return false" class="btn btn-warning btn-lg button-text">
          <i class="fa fa-facebook-square" style="color: white"></i><strong> Share</strong>
        </a>
        <a href="https://twitter.com/intent/tweet?original_referer=http%3A%2F%2Flocalhost%3A3000%2Fcome_back_later&amp;text=What%20picture%20should%20you%20use%20on%20Tinder%3F%20%40Tinder_Genius%20gives%20you%20the%20answer%3A&amp;tw_p=tweetbutton&amp;url=http%3A%2F%2Fwww.tindergenius.com" class="btn btn-success btn-lg button-text">
          <i class="fa fa-twitter" style="color: #139ae9"></i><strong style="color: #333333"> Tweet</strong>
        </a>
      </div>
    </div>

    <div class="col-md-4 col-xl-3">
      <div class="text-center">
        <div class="text-block">
          <img src="http://s30.postimg.org/jzfhlp5c1/mojito.png" height="200" width="200"><br/>
          <p class="text-center">If you're patient, go drink a Mojito<br/><span style="font-size: 16px;">(with your Tinder match?)</span></p>
        </div>
        <a target="blank" href="https://www.google.com/maps?q=mojitos+near+<%= current_user.city.gsub(/\s/,'+').gsub(/\,/,'+') %>" class="btn btn-default btn-lg">
          <i style="color: white" class="button-text"></i><i class="fa fa-thumbs-up"></i><strong> Oh yeah!</strong>
        </a>
      </div>
    </div>

  </div>
</div>

<div class="text-center" style="font-family: Source Sans Pro; padding-top:40px;padding-bottom:20px;">
  <% if user_signed_in? %>
    <%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %>
  <% end %>
</div>


<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/campaigns/results.html.erb
<% if @campaign.status == false %>

  <%= render 'campaign_results' %>

<% else %>

  <%= render 'no_results_yet' %>

<% end %>

<div class="text-center" style="font-family: Source Sans Pro; padding-top:40px; padding-bottom:20px;">
  <% if user_signed_in? %>
    <%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %>
  <% end %>
</div>

app/views/campaigns/show.html.erb
<% content_for(:title) do %>
   Vote
<% end %>

<h1 id="titleup" > <strong>Which one do you prefer?</strong> </h1>

<div class="container">

  <div class="row">

    <div class="col-xs-10 col-xs-offset-1 col-md-offset-0 col-md-6">
      <div id="pic1" class="stack twisted text-center">
        <%= link_to campaign_votes_path(
          vote: {
            voted_picture_id: @campaign.picture_a_id
          },
          campaign_id: @campaign.id),
          method: :post do %>
          <%= image_tag (Picture.find(@campaign.picture_a_id).file), size: "300x300" %>
        <% end %>
      </div>
    </div>
  </br>
     <div class="col-xs-10 col-xs-offset-1 col-md-offset-0  col-md-6">
      <div id="pic2" class="stack twisted text-center">
        <%= link_to campaign_votes_path(
          vote: {
            voted_picture_id: @campaign.picture_b_id,
          },
          campaign_id: @campaign.id),
          method: :post do %>
          <%= image_tag (Picture.find(@campaign.picture_b_id).file), size: "300x300" %>
        <% end %>
      </div>
    </div>

</div>


<div id="prog" class="text-center">
  <% if current_user.votes.length > 4 %>
   <div class="text-votes">
     Continue voting: the more you vote, the faster you'll get your results!<br/>
     (<%= current_user.votes.length %> votes)
   </div>
 <br/>
   <%= link_to 'Done', finish_voting_path %>
 <% else %>
   <div class="text-votes">
     Only <%= 5 - current_user.votes.length %> votes left !
   </div>
    <br/>
    <br/>
    <div class="progress">
      <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: <%= ((current_user.votes.length + 1) / 6.0) * 100 %>%">
      </div>
    </div>
</div>

<% end %>